baseURL = "https://fuzzylogiq.github.io/"
languageCode = "en-gb"
title = "fuzzylogiq's blog"
theme = "hugo-journal"
disqusShortname = "fuzzylogiq-github-io"
googleAnalytics = "UA-111236653-1"
[author]
  name = "Ben Goodstein"
  homepage = "https://fuzzylogiq.github.io/"
[blackfriday]
  extension = ["footnotes"]
[params]
  description = "a macOS and Linux systems administrator's blog"
  githubUsername = "fuzzylogiq"
  twitterUsername = "fuzzylogiq"
  tagline = "the latest blitherings"
[params.work]
  jobTitle = "Technical Leader (Apple)"
  company = "University of Oxford"
  companyUrl = "https://ox.ac.uk"
